export default function Home() {
  return <main>
    <header className="header"><a className="logo" href="#top"><b>C</b><span>CLEBO<small>CONSULTING</small></span></a><nav><a href="#tjanster">Tjänster</a><a href="#om">Om Leonard</a><a href="#arbetssatt">Arbetssätt</a><a className="navCta" href="#kontakt">Kontakt</a></nav></header>
    <section className="hero" id="top"><div className="heroCopy"><p className="kicker">Expertgranskning · Familjerätt · Socialt arbete</p><h1>När barnets bästa kräver <em>mer än en åsikt.</em></h1><p className="lead">Oberoende, forskningsbaserad granskning av socialtjänstens utredningar i vårdnadstvister och LVU-ärenden.</p><div className="actions"><a className="button" href="#kontakt">Beskriv ditt ärende <span>→</span></a><a href="#tjanster" className="under">Så kan Clebo hjälpa</a></div><div className="facts"><div><strong>Fil. dr</strong><span>Forskarkompetens</span></div><div><strong>Opartisk</strong><span>Expertgranskning</span></div><div><strong>Sedan 2014</strong><span>Clebo Consulting AB</span></div></div></div><div className="heroImage"><img src="/family-hands.jpg" alt="Ett barns hand vilar tryggt i en vuxens hand"/><div className="note"><span>01</span><p>Struktur, evidens och ett tydligt barnperspektiv.</p></div></div></section>
    <section className="statement"><p>Komplexa familjerättsliga frågor behöver granskas med både <em>vetenskaplig noggrannhet</em> och förståelse för människan bakom materialet.</p></section>
    <section className="services" id="tjanster"><div className="sectionHead"><p className="kicker">Tjänster</p><h2>Från omfattande material till en tydlig bedömning.</h2></div><div className="serviceGrid"><article><span>01</span><h3>Expertgranskning</h3><p>Oberoende genomgång av socialtjänstens utredningar, metodval, underlag och slutsatser.</p></article><article><span>02</span><h3>Riskbedömning</h3><p>Forskningsbaserad analys av risk- och skyddsfaktorer i vårdnadstvister och barnavårdsärenden.</p></article><article><span>03</span><h3>Second opinion</h3><p>En fristående bedömning som synliggör styrkor, brister och centrala frågor i materialet.</p></article><article><span>04</span><h3>Utbildning</h3><p>Föreläsningar inom socialt arbete, psykologi, utredningsmetodik och familjerättsliga processer.</p></article></div></section>
    <section className="about" id="om"><div className="aboutImage"><img src="/research-desk.jpg" alt="Arbetsplats för noggrann analys"/><span>Vetenskap i praktiken</span></div><div className="aboutCopy"><p className="kicker">Leonard Ngaosuvan</p><h2>Forskning som gör skillnad i verkliga ärenden.</h2><p className="large">Leonard Ngaosuvan är filosofie doktor och familjerättsforskare med särskild kompetens inom vårdnadstvister, riskbedömning och granskning av barnavårdsutredningar.</p><p>Clebo Consulting förenar samhällsvetenskaplig forskning med praktisk förståelse för utredningsprocessen. Målet är att göra komplexa underlag begripliga, synliggöra metodfrågor och ge ett sakligt beslutsunderlag.</p><div className="chips"><span>Familjerättsforskning</span><span>Socialt arbete & psykologi</span><span>Utredningsmetodik</span></div></div></section>
    <section className="process" id="arbetssatt"><div className="sectionHead"><p className="kicker">Arbetssätt</p><h2>Grundligt, transparent och steg för steg.</h2></div><div className="steps"><article><b>1</b><h3>Inledande kontakt</h3><p>Du beskriver ärendet och vilket material som finns. Uppdragets omfattning tydliggörs.</p></article><article><b>2</b><h3>Systematisk analys</h3><p>Underlaget granskas med fokus på metod, evidens, riskfaktorer, resonemang och slutsatser.</p></article><article><b>3</b><h3>Tydlig återkoppling</h3><p>Du får en strukturerad bedömning som skiljer fakta, observationer och slutsatser åt.</p></article></div></section>
    <section className="insight"><div><p className="kicker">Perspektiv</p><blockquote>“En bra granskning handlar inte om att välja sida. Den handlar om att pröva om slutsatserna faktiskt bär.”</blockquote></div><img src="/analysis-work.jpg" alt="Anteckningar och dator vid ett analysarbete"/></section>
    <section className="contact" id="kontakt"><div><p className="kicker">Kontakt</p><h2>Ta ett första, förutsättningslöst steg.</h2><p>Beskriv kort vad ärendet gäller och vilket underlag som finns. All kontakt behandlas med diskretion.</p></div><div className="contactCard"><small>E-post</small><a href="mailto:leo@cleboconsulting.se">leo@cleboconsulting.se</a><small>Adress</small><address>Solberga Ängsväg 15<br/>125 44 Älvsjö</address><small>Företagsuppgifter</small><p>Clebo Consulting AB<br/>Org.nr 556986-9992</p></div></section>
    <footer><a className="logo" href="#top"><b>C</b><span>CLEBO<small>CONSULTING</small></span></a><p>Expertgranskning inom familjerätt och socialt arbete.</p><div><a href="mailto:leo@cleboconsulting.se">E-post</a><a href="#top">Till toppen ↑</a></div><small className="credits">Foto: Liane Metzler, Nick Morrison & Dan Dimmock / Unsplash</small></footer>
  </main>;
}
